
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Nov  1 2025 14:48:37 IST (Nov  1 2025 09:18:37 UTC)

// Verification Directory fv/dedee 

module hamming_encoder(data_in, code_out);
  input [3:0] data_in;
  output [6:0] code_out;
  wire [3:0] data_in;
  wire [6:0] code_out;
  wire n_1, n_2, n_3, n_4, n_5;
  OAI21XL g77__2398(.A0 (n_2), .A1 (data_in[1]), .B0 (n_4), .Y
       (code_out[6]));
  OAI21XL g78__5107(.A0 (n_1), .A1 (data_in[0]), .B0 (n_5), .Y
       (code_out[5]));
  OAI21XL g79__6260(.A0 (n_1), .A1 (data_in[1]), .B0 (n_3), .Y
       (code_out[3]));
  NAND2XL g80__4319(.A (data_in[0]), .B (n_1), .Y (n_5));
  NAND2XL g81__8428(.A (data_in[1]), .B (n_2), .Y (n_4));
  NAND2XL g82__5526(.A (data_in[1]), .B (n_1), .Y (n_3));
  XNOR2X1 g83__6783(.A (data_in[0]), .B (data_in[3]), .Y (n_2));
  XNOR2X1 g84__3680(.A (data_in[2]), .B (data_in[3]), .Y (n_1));
endmodule

module dedee(clk, data_in, data_out, encoded_data, syndrome,
     error_flag);
  input clk;
  input [3:0] data_in;
  output [3:0] data_out;
  output [6:0] encoded_data;
  output [2:0] syndrome;
  output error_flag;
  wire clk;
  wire [3:0] data_in;
  wire [3:0] data_out;
  wire [6:0] encoded_data;
  wire [2:0] syndrome;
  wire error_flag;
  wire [6:0] code_temp;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2;
  assign error_flag = 1'b0;
  assign syndrome[0] = 1'b0;
  assign syndrome[1] = 1'b0;
  assign syndrome[2] = 1'b0;
  assign encoded_data[0] = data_out[0];
  assign encoded_data[1] = data_out[1];
  assign encoded_data[2] = data_out[2];
  assign encoded_data[4] = data_out[3];
  hamming_encoder u1(.data_in (data_in), .code_out ({code_temp[6:5],
       UNCONNECTED2, code_temp[3], UNCONNECTED1, UNCONNECTED0,
       UNCONNECTED}));
  DFFQXL \encoded_reg_reg[5] (.CK (clk), .D (code_temp[5]), .Q
       (encoded_data[5]));
  DFFQXL \encoded_reg_reg[3] (.CK (clk), .D (code_temp[3]), .Q
       (encoded_data[3]));
  DFFQXL \encoded_reg_reg[6] (.CK (clk), .D (code_temp[6]), .Q
       (encoded_data[6]));
  DFFQXL \decoded_reg_reg[3] (.CK (clk), .D (data_in[0]), .Q
       (data_out[3]));
  DFFQXL \decoded_reg_reg[2] (.CK (clk), .D (data_in[1]), .Q
       (data_out[2]));
  DFFQXL \decoded_reg_reg[0] (.CK (clk), .D (data_in[3]), .Q
       (data_out[0]));
  DFFQXL \decoded_reg_reg[1] (.CK (clk), .D (data_in[2]), .Q
       (data_out[1]));
endmodule

